#!/bin/bash

DIR=$(dirname "$(readlink -f "$0")")

# -------------------------------------------------------------------------------
# stream-monitor
# -------------------------------------------------------------------------------
sudo apt update # update
sudo apt install jq -y # global
sudo apt install -y libraspberrypi-bin # utiles
sudo apt install stress-ng -y

# python
pip install python-dotenv

# permission
chmod +x "$DIR"/monitor
chmod +x "$DIR"/utiles/log
chmod +x "$DIR"/tools/tools

# -------------------------------------------------------------------------------
# chzzk-rekoda
# -------------------------------------------------------------------------------
echo "Check if uv is installed"
if ! command -v uv > /dev/null 2>&1; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
    source "$HOME/.local/bin/env"
fi

# permission
chmod +x "$DIR"/platform/chzzk/chzzk
chmod +x "$DIR"/platform/chzzk/kill

# -------------------------------------------------------------------------------
# twitcasting
# -------------------------------------------------------------------------------
# permission
chmod +x "$DIR"/platform/twitcasting/twitcasting
chmod +x "$DIR"/platform/twitcasting/kill


# -------------------------------------------------------------------------------
# X
# -------------------------------------------------------------------------------
# permission
chmod +x "$DIR"/platform/X/X
chmod +x "$DIR"/platform/X/kill