#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

while true; do
    clear

    printf "0. Exit\n"
    printf "1. current state\n"
    printf "2. utiles\n"
    printf "3. chzzk setting\n"
    printf "\n"
    read -p "commend: " cmd


    if [ "$cmd" = "0" ]; then
        break
    elif [ "$cmd" = "1" ]; then
        watch -n 1 "$SCRIPT_DIR"/utiles/log
    elif [ "$cmd" = "2" ]; then
        "$SCRIPT_DIR"/tools/utiles
    elif [ "$cmd" = "3" ]; then
        cd "$SCRIPT_DIR"/Chzzk-Rekoda
        ./settings
        exit 0 
    else
        echo "Invalid command."
        sleep 1
    fi
done