#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

while true; do
    clear

    printf "0. Exit\n"
    printf "1. CPU temperature\n"
    printf "2. CPU stress test\n"
    printf "\n"
    read -p "command: " cmd

    if [ "$cmd" = "0" ]; then
        break
    elif [ "$cmd" = "1" ]; then
        "$SCRIPT_DIR"/cpu-temperture
    elif [ "$cmd" = "2" ]; then
        "$SCRIPT_DIR"/cpu-stress-test
    else
        echo "Invalid command."
        sleep 1
    fi
done
